remote_theme: thuhcsi/slate
title: Demos of SnakeGAN-Leveraging DDSP Prior Knowledge and Periodic Inductive Bias
description: Submitted to ICME-2023.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
